import type { Metadata } from "next";
import { open_sans } from "@/components/fonts";
import { cn } from "@/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          open_sans.variable,
        )}
      >
        <nav className="sticky top-0 z-10 w-full bg-slate-200/50 backdrop-blur-sm py-2">
          <h1 className="text-slate-800 font-semibold text-2xl text-center">
            Quake Data Visulization
          </h1>
        </nav>
        <div className="w-full p-2 sm:container">{children}</div>
      </body>
    </html>
  );
}
